development:
  adapter: postgresql
  encoding: unicode
  database: quickbooks_app_development
  pool: 5
  username: daimler456
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quickbooks_app_test
  pool: 5
  username: daimler456
  password:
